### ISSUE TITLE
Standard DOM apis and TS bridge helper

### ISSUE THREAD

**Issue by clsource** [gleam-lang/javascript#3]
Currently if you want to use a library that is JS only, you would need to create the ffi bindings for it. A DOM ffi for the standard browser apis (document, window, etc) would be awesome.

It would be really cool if some tool existed that make conversion from TS definitions to Gleam ffi bridges, and ease the bridging part. 

- https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.generated.d.ts
- https://github.com/microsoft/TypeScript-DOM-lib-generator

Maybe something like https://github.com/purescript-web can be used too 💯 

I find Gleam to be a nicer alternative to Typescript. I would love to be used in Phoenix Hooks instead of typescript.

I made a simple example  and my only concern is the amount of FFI bridges that are needed.
If something was available to automate this process would be much appreciated.

https://github.com/ElixirCL/gleamphx

thanks 👍

**Comment by lpil** [comment]
Hello! I agree it would be really great to have some DOM bindings. I personally would use these for small projects over React etc.

The DOM API is very large and complex so I think it would be best for people experiment with different API designs and see what works best rather than having one official design in here. It is very likely that anything we design today someone else will make a much better design tomorrow.

Generating code from TypeScript sounds very interesting, though we would have some difficulty in that there are many features in the TypeScript type system that we don't have in Gleam, most notably subtyping.

**Comment by clsource** [comment]
Created a simple Proof of Concept https://github.com/ElixirCL/example-gleam-web-dom-ffi

**Comment by clsource** [comment]
I found Kotlin to have many wrappers too, that could serve as an example.

- https://github.com/JetBrains/kotlin-wrappers
- https://github.com/kotlin/dukat
- https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by lpil** [comment]
I'm going to close this as this would need to be a different package, as this one can run in JS environment where there is no DOM. Thank you
